name: Hello World

on: push

jobs:
 hello-job:
  runs-on: ubuntu-latest
  steps:
   - name: copying the log file
     uses: actions/checkout@v4

   - name: copying the file 
     run:  cp ./text.log  /tmp

   - name: running ls to validate
     run: ls -al





# Workflow should have a Job named - hello-job
# a. Run Job on - ubuntu-latest runner
# b. Job has 1 step named - Echo text
# c. Run a command - echo "Hello, world!"